artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/267667dc117f42838e2e229a06cd4ae9/artifacts
end_time: 1610458724604
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 267667dc117f42838e2e229a06cd4ae9
run_uuid: 267667dc117f42838e2e229a06cd4ae9
source_name: ''
source_type: 4
source_version: ''
start_time: 1610458713889
status: 3
tags: []
user_id: Mike
