artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/370eac0a3d5142a1b7660cd6e634e8ec/artifacts
end_time: 1608643939207
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 370eac0a3d5142a1b7660cd6e634e8ec
run_uuid: 370eac0a3d5142a1b7660cd6e634e8ec
source_name: ''
source_type: 4
source_version: ''
start_time: 1608643929354
status: 3
tags: []
user_id: Mike
