artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/3cd2f66ca1fd441b8107b5731e9bccd5/artifacts
end_time: 1610460853840
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 3cd2f66ca1fd441b8107b5731e9bccd5
run_uuid: 3cd2f66ca1fd441b8107b5731e9bccd5
source_name: ''
source_type: 4
source_version: ''
start_time: 1610460843121
status: 4
tags: []
user_id: Mike
