artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/7a8c657a9f6e4af4b0c75e3b3c10c303/artifacts
end_time: 1610982790351
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 7a8c657a9f6e4af4b0c75e3b3c10c303
run_uuid: 7a8c657a9f6e4af4b0c75e3b3c10c303
source_name: ''
source_type: 4
source_version: ''
start_time: 1610982723103
status: 3
tags: []
user_id: Mike
