artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/ab99a32082ce4322a7e3450f3c13e281/artifacts
end_time: 1606554373776
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: ab99a32082ce4322a7e3450f3c13e281
run_uuid: ab99a32082ce4322a7e3450f3c13e281
source_name: ''
source_type: 4
source_version: ''
start_time: 1606554344891
status: 3
tags: []
user_id: Mike
