artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/08e0f6f840cc43eebaae10c83c05df91/artifacts
end_time: 1610461014752
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 08e0f6f840cc43eebaae10c83c05df91
run_uuid: 08e0f6f840cc43eebaae10c83c05df91
source_name: ''
source_type: 4
source_version: ''
start_time: 1610461003576
status: 3
tags: []
user_id: Mike
