artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/ca986df220254571b764373a2b878dcd/artifacts
end_time: 1613566908252
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ca986df220254571b764373a2b878dcd
run_uuid: ca986df220254571b764373a2b878dcd
source_name: ''
source_type: 4
source_version: ''
start_time: 1613566874395
status: 3
tags: []
user_id: Mike
