artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/cecc5d44171c43adaa3105aa8d4d605b/artifacts
end_time: 1613566748067
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: cecc5d44171c43adaa3105aa8d4d605b
run_uuid: cecc5d44171c43adaa3105aa8d4d605b
source_name: ''
source_type: 4
source_version: ''
start_time: 1613566714482
status: 3
tags: []
user_id: Mike
