artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/a38b9b3a71c8471e8a5ee737ecea26d8/artifacts
end_time: 1610460441993
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: a38b9b3a71c8471e8a5ee737ecea26d8
run_uuid: a38b9b3a71c8471e8a5ee737ecea26d8
source_name: ''
source_type: 4
source_version: ''
start_time: 1610460430996
status: 3
tags: []
user_id: Mike
