artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/9e52c620226b48acac72abcc2be74e5e/artifacts
end_time: 1606827137326
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 9e52c620226b48acac72abcc2be74e5e
run_uuid: 9e52c620226b48acac72abcc2be74e5e
source_name: ''
source_type: 4
source_version: ''
start_time: 1606827127949
status: 3
tags: []
user_id: Mike
