artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/f73726f1960e4305a76e4f1f0a5a788d/artifacts
end_time: 1612532269565
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f73726f1960e4305a76e4f1f0a5a788d
run_uuid: f73726f1960e4305a76e4f1f0a5a788d
source_name: ''
source_type: 4
source_version: ''
start_time: 1612532207498
status: 3
tags: []
user_id: Mike
