artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/cc6d4219406a4a508a8620b1aba75664/artifacts
end_time: 1610981642220
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: cc6d4219406a4a508a8620b1aba75664
run_uuid: cc6d4219406a4a508a8620b1aba75664
source_name: ''
source_type: 4
source_version: ''
start_time: 1610981545394
status: 3
tags: []
user_id: Mike
