artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/ad0b55715a1e450fb45e47f6934833f8/artifacts
end_time: 1612965100051
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ad0b55715a1e450fb45e47f6934833f8
run_uuid: ad0b55715a1e450fb45e47f6934833f8
source_name: ''
source_type: 4
source_version: ''
start_time: 1612964917812
status: 3
tags: []
user_id: Mike
