artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/aa689aed18344e7a991777f3e3c34a56/artifacts
end_time: 1610464108767
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: aa689aed18344e7a991777f3e3c34a56
run_uuid: aa689aed18344e7a991777f3e3c34a56
source_name: ''
source_type: 4
source_version: ''
start_time: 1610464016089
status: 3
tags: []
user_id: Mike
