artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/3f7c56c28eec45b8acd54e8bc7658be6/artifacts
end_time: 1607765433957
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3f7c56c28eec45b8acd54e8bc7658be6
run_uuid: 3f7c56c28eec45b8acd54e8bc7658be6
source_name: ''
source_type: 4
source_version: ''
start_time: 1607765363451
status: 3
tags: []
user_id: Mike
