artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/b3aab78d26cf4695a3c78a173c3d4b1a/artifacts
end_time: 1612539001819
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b3aab78d26cf4695a3c78a173c3d4b1a
run_uuid: b3aab78d26cf4695a3c78a173c3d4b1a
source_name: ''
source_type: 4
source_version: ''
start_time: 1612538918947
status: 3
tags: []
user_id: Mike
