artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/07d0ea030c88479bae45402acffce301/artifacts
end_time: 1609670025326
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 07d0ea030c88479bae45402acffce301
run_uuid: 07d0ea030c88479bae45402acffce301
source_name: ''
source_type: 4
source_version: ''
start_time: 1609669943821
status: 3
tags: []
user_id: Mike
