artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/26ebb75fa2c14e64936cc05c7beae6c5/artifacts
end_time: 1610460124470
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 26ebb75fa2c14e64936cc05c7beae6c5
run_uuid: 26ebb75fa2c14e64936cc05c7beae6c5
source_name: ''
source_type: 4
source_version: ''
start_time: 1610460113676
status: 3
tags: []
user_id: Mike
