artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/3ce641d558d8413d9a428d7bdc7b9ad2/artifacts
end_time: 1612687061442
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3ce641d558d8413d9a428d7bdc7b9ad2
run_uuid: 3ce641d558d8413d9a428d7bdc7b9ad2
source_name: ''
source_type: 4
source_version: ''
start_time: 1612686991990
status: 3
tags: []
user_id: Mike
