artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/9be4398c2f3842d79d48f00ffdeb9901/artifacts
end_time: 1612686564193
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9be4398c2f3842d79d48f00ffdeb9901
run_uuid: 9be4398c2f3842d79d48f00ffdeb9901
source_name: ''
source_type: 4
source_version: ''
start_time: 1612686563088
status: 4
tags: []
user_id: Mike
