artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/098d558fbc994c869e4dcfa2db891619/artifacts
end_time: 1610460023784
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 098d558fbc994c869e4dcfa2db891619
run_uuid: 098d558fbc994c869e4dcfa2db891619
source_name: ''
source_type: 4
source_version: ''
start_time: 1610460013192
status: 4
tags: []
user_id: Mike
