artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/6e8565d49fae479cae1590162cc74947/artifacts
end_time: 1606828346533
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 6e8565d49fae479cae1590162cc74947
run_uuid: 6e8565d49fae479cae1590162cc74947
source_name: ''
source_type: 4
source_version: ''
start_time: 1606828300863
status: 3
tags: []
user_id: Mike
