artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/b480bf95ac94488e9619c742896d2bc1/artifacts
end_time: 1612685893130
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b480bf95ac94488e9619c742896d2bc1
run_uuid: b480bf95ac94488e9619c742896d2bc1
source_name: ''
source_type: 4
source_version: ''
start_time: 1612685832035
status: 3
tags: []
user_id: Mike
