artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/613df02e4e134025ac4ea83e2bb6d15d/artifacts
end_time: 1605518121858
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 613df02e4e134025ac4ea83e2bb6d15d
run_uuid: 613df02e4e134025ac4ea83e2bb6d15d
source_name: ''
source_type: 4
source_version: ''
start_time: 1605518116296
status: 4
tags: []
user_id: Mike
