artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/8e50843c0db44b5eaeec0aa3f4d3de97/artifacts
end_time: 1613563405862
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 8e50843c0db44b5eaeec0aa3f4d3de97
run_uuid: 8e50843c0db44b5eaeec0aa3f4d3de97
source_name: ''
source_type: 4
source_version: ''
start_time: 1613563338373
status: 3
tags: []
user_id: Mike
