artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/923c6cfddafa4e258757d90474e71eb5/artifacts
end_time: 1612964853186
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 923c6cfddafa4e258757d90474e71eb5
run_uuid: 923c6cfddafa4e258757d90474e71eb5
source_name: ''
source_type: 4
source_version: ''
start_time: 1612964791841
status: 3
tags: []
user_id: Mike
