artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/0d3f0f9d80064ecda905039e4f3b3ea7/artifacts
end_time: 1613566457577
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 0d3f0f9d80064ecda905039e4f3b3ea7
run_uuid: 0d3f0f9d80064ecda905039e4f3b3ea7
source_name: ''
source_type: 4
source_version: ''
start_time: 1613566413578
status: 3
tags: []
user_id: Mike
