artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/eb7ca48e28d3465084ab3e16bbf84d0e/artifacts
end_time: 1613563928052
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: eb7ca48e28d3465084ab3e16bbf84d0e
run_uuid: eb7ca48e28d3465084ab3e16bbf84d0e
source_name: ''
source_type: 4
source_version: ''
start_time: 1613563835811
status: 3
tags: []
user_id: Mike
