artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/c2662c3cbb9b47518281d1bb8d6f8fef/artifacts
end_time: 1609665203064
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: c2662c3cbb9b47518281d1bb8d6f8fef
run_uuid: c2662c3cbb9b47518281d1bb8d6f8fef
source_name: ''
source_type: 4
source_version: ''
start_time: 1609665192912
status: 3
tags: []
user_id: Mike
