artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/1381102560a04bfd969b55469a5aca2b/artifacts
end_time: 1612964298025
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 1381102560a04bfd969b55469a5aca2b
run_uuid: 1381102560a04bfd969b55469a5aca2b
source_name: ''
source_type: 4
source_version: ''
start_time: 1612964254559
status: 3
tags: []
user_id: Mike
