artifact_uri: file:///D:/Michael/five_minute_midas/mlflow/0/98708470d1f847a2af716b1fa1e96e5c/artifacts
end_time: 1613566839707
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 98708470d1f847a2af716b1fa1e96e5c
run_uuid: 98708470d1f847a2af716b1fa1e96e5c
source_name: ''
source_type: 4
source_version: ''
start_time: 1613566777842
status: 3
tags: []
user_id: Mike
